name: translation-env  
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8  
  - pandas
  - pytorch
  - torchvision
  - torchaudio
  - nltk
  - scikit-learn
  - jsonschema  
  - argparse  
  - pip
  - pip:
    - tqdm  
